services:
  db:
    image: postgres:15
    container_name: barbearia-db
    restart: always
    environment:
      POSTGRES_USER: barbearia
      POSTGRES_PASSWORD: barbearia
      POSTGRES_DB: barbearia
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: barbearia-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080" # Porta padrão do Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/barbearia
      SPRING_DATASOURCE_USERNAME: barbearia
      SPRING_DATASOURCE_PASSWORD: barbearia
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
