spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/barbearia}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:barbearia}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:barbearia}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jmx.enabled=false
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
1h in millisecond
security.jwt.expiration-time=3600000
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
